### ISSUE TITLE
[AMO Signed] Issue with signed AMO in 32 bit core interface   

### ISSUE THREAD

**Issue by khandelwaltanuj** [openhwgroup/cv-hpdcache#17]
Hello @cfuguet 

In the case of 32 bit core interface, the signed AMO do not seems to work correctly. 

@cfuguet is already aware of the issue. 

Thanks and Regards
Tanuj Khandelwal

**Comment by cfuguet** [comment]
This should be now fixed. I close the issue but feel free to reopen it if you still have the issue
