### ISSUE TITLE
[PLRU Issue] In case of CMO_PREFETCH plru behaves differently in case if HIT or MISS 

### ISSUE THREAD

**Issue by khandelwaltanuj** [openhwgroup/cv-hpdcache#18]
Hello,

Following observation are made in the case of CMO_PREFETCH (prefetch_updt_plru == 1) 

1. in case of hit PLRU is not updated 
2. in case of miss PLRU is updated once the read memory response is received. 

This seems inconsistant. Can you please take a look at it ? 

Thanks and regards
Tanuj Khandelwal

**Comment by khandelwaltanuj** [comment]
Hi @cfuguet 

Do you have any update on this ? 

Thanks and Regards
Tanuj Khandelwal

**Comment by cfuguet** [comment]
Hello @khandelwaltanuj,

I forgot about this one. Yes, this should be fixed. I will do it.

The fix will do the following:

- In case of PREFETCH hit, the PLRU is updated if prefetch_updt_plru == 1
- In case of PREFETCH miss, the PLRU is updated at refill time if prefetch_updt_plru == 1

Thanks for spotting this out

**Comment by cfuguet** [comment]
Fixed in commit ab4b7ea04173db73efa6f47fbcea9da812a6f65d

**Comment by khandelwaltanuj** [comment]
Hi @cfuguet 

This fix is working in my regression. I am keeping it open, as I am not able to merge the new version to TB yet. 

Regards
Tanuj Khandelwal

**Comment by khandelwaltanuj** [comment]
Hi @cfuguet 

Thanks for closing this issue. I was able to merge the TB fix this morning. And it is passing in regression

Regards
Tanuj
