### ISSUE TITLE
Bender file and question w.r.t. hybrid write-back/write-through policy

### ISSUE THREAD

**Issue by michael-platzer** [openhwgroup/cv-hpdcache#19]
Hi,

thanks a lot for this very neat project and the nice inline documentation!

I see that this repository does not have a bender file and while it is included as a submodule in the CVA6 repository, as far as I have seen its sources do not show up in CVA6's bender file either.

Would you accept a pull request that adds a bender file to this repository?

Also, I was wondering whether the hybrid write-back/write-through policy that [is mentioned in this presentation](https://youtu.be/ODHA-wPOmW0?si=dxOVTtEVx67mxxIu&t=372) is still being worked on and what the current status is.

Thanks,
Michael

**Comment by cfuguet** [comment]
Hello @michael-platzer,

Yes, I'll be glad to accept a pull request with the Bender file. However, if you do, can you please give me some pointers to read about how to use Bender ? That way I will be able to update and test the bender file, if needed, in future releases of the HPDcache.

Currently, I'm used to use Flist files or a custom metadata file we have in CEA...

Regarding the Write-Back/Write-Through feature, I'm currently working on that but not full time. I target a first validated (but not fully verified) version with that feature before this summer.

**Comment by michael-platzer** [comment]
@cfuguet Thanks a lot for the quick response!

> Yes, I'll be glad to accept a pull request with the Bender file. However, if you do, can you please give me some pointers to read about how to use Bender ? That way I will be able to update and test the bender file, if needed, in future releases of the HPDcache.

Sure, Bender is a tool for managing dependencies in RTL projects. It uses a manifest file named `Bender.yml` which defines the source files and dependencies of a project. It is an open-source tool maintained by the PULP team and used in many OpenHW Group projects. You can find its documentation in this repository: https://github.com/pulp-platform/bender

I will open a pull request and try to summarize the essential features in the description.

> Regarding the Write-Back/Write-Through feature, I'm currently working on that but not full time. I target a first validated (but not fully verified) version with that feature before this summer.

That sounds amazing, thanks a lot for the update!

**Comment by cfuguet** [comment]
Solved by PR #20 from @michael-platzer.

Thank you !
