### ISSUE TITLE
[Question] PLRU in the case of error responses 

### ISSUE THREAD

**Issue by khandelwaltanuj** [openhwgroup/cv-hpdcache#32]
Hi César,

If I understand well, as per the new specification, the PLRU is updated at the time a read miss is observed (and not during the refill response). So it means that even if a response from the memory is an error, the PLRU is updated ? 

Thanks and regards
Tanuj Khandelwal

**Comment by cfuguet** [comment]
Hello @khandelwaltanuj,

No, the victim cacheline is selected at the time of the miss (read or store-write-back), but the PLRU update is done at refill time.

The cache makes sure that a selected victim entry is not re-selected again as it sets the "fetch" bit in the directory to indicate that the entry has been pre-selected and will be replaced when the refill response is back.

**Comment by khandelwaltanuj** [comment]
Hello

Thanks for your reponse.

Regards
Tanuj
