### ISSUE TITLE
[Document] The section explaining PLRU seems incomplete

### ISSUE THREAD

**Issue by khandelwaltanuj** [openhwgroup/cv-hpdcache#34]
Hi @cfuguet 

It seems that the section which explains PLRU algorithm (https://github.com/openhwgroup/cv-hpdcache/blob/master/docs/source/architecture.rst#replacement-policy) does not take into account the write policy. 
As per my understading PLRU behves differently in the case of write back or write through policy. 

Can you please take a look at it ? 

Regards
Tanuj Khandelwal

**Comment by cfuguet** [comment]
Yes, CMO_PREFETCH does update the PLRU bits. I will write an explicit sentence in the document.

**Comment by cfuguet** [comment]
I updated the documentation @khandelwaltanuj .

Please let me know if it is OK and then please close the issue.

Thank you !

**Comment by khandelwaltanuj** [comment]
Thanks @cfuguet 

This looks pretty good. 

Regards
Tanuj
