### ISSUE TITLE
[PARAMS] Issue with CONF_HPDCACHE_WORD_WIDTH parameter

### ISSUE THREAD

**Issue by khandelwaltanuj** [openhwgroup/cv-hpdcache#8]
Hello,

HPDcache doesn't compile with following parameters.

+        `define CONF_HPDCACHE_WORD_WIDTH 128
+        `define CONF_HPDCACHE_CL_WORDS 4

@cfuguet  Can you please take a look please ?

Thanks and Regards
Tanuj

**Comment by cfuguet** [comment]
Hello @khandelwaltanuj,

Thank you for reporting this issue, the HPDCache supports CONF_HPDCACHE_WORD_WIDTH = (32 or 64). If you need wider interfaces, use the CONF_HPDCACHE_REQ_WORDS > 1. For example by using CONF_HPDCACHE_REQ_WORDS = 4 and CONF_HPDCACHE_WORD_WIDTH = 64, the HPDcache will implement interfaces of 256 bits.
