### ISSUE TITLE
[PLRU] The plru in the case of AMOs is not being updated properly.

### ISSUE THREAD

**Issue by khandelwaltanuj** [openhwgroup/cv-hpdcache#9]
Hello,

The PLRU in some cases of AMOs is not being updated properly. 
It seems the problem is comming from the fact that amo_dir_match signal arrives at the same time as amo_plru_update 

@cfuguet can you please take a look please ? 

Thanks and Regards
Tanuj

**Comment by cfuguet** [comment]
Hi @khandelwaltanuj,

Thank you for reporting this issue. It should be now fixed by commit 192a8d1.

Can you please try and close the issue if it is solved ?

Thanks !

**Comment by khandelwaltanuj** [comment]
Hi @cfuguet 

My regression is passing now. Thanks for the fix. 

Regards
Tanuj
